# name: Build Docker image

# on:
#   push:
#     branches:
#       - master
#   workflow_dispatch:
#   pull_request:

# jobs:
#   # Build docker image for all events, but never push to any registry.
#   build-push-docker:
#     runs-on: ubuntu-latest
#     # permissions can technically be reduced now, but leaving them is harmless.
#     permissions:
#       contents: read
#       packages: write
#       attestations: write
#       id-token: write

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Docker meta
#         id: meta
#         uses: docker/metadata-action@v5
#         with:
#           images: |
#             ghcr.io/${{ github.repository_owner }}/litecoin-core
#           tags: |
#             # creates a tag for each push
#             type=sha,event=push

#             # creates a tag for each pr
#             type=ref,event=pr

#             # set latest tag for default branch
#             type=raw,value=latest,enable={{is_default_branch}}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Login to GHCR
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - name: Build Docker image (no push)
#         uses: docker/build-push-action@v6
#         with:
#           push: false
#           tags: ${{ steps.meta.outputs.tags }}
#           # Docker build cache (still fine to use; pulls from GHCR but does not push)
#           cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/litecoin-core:latest
#           cache-to: type=inline
